src/brouwers/albums/urls.py
from django.urls import path, re_path
from django.views.generic import RedirectView

# from .ajax_views import RotateView
from .views import (
    AlbumCreateView,
    AlbumDeleteView,
    AlbumDetailView,
    AlbumDownloadView,
    AlbumListView,
    AlbumRestoreView,
    AlbumUpdateView,
    IndexView,
    MyAlbumsView,
    PhotoDeleteView,
    PhotoDetailView,
    PhotoRestoreView,
    PhotoUpdateView,
    PreferencesUpdateView,
    SearchView,
    UploadView,
)

app_name = "albums"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("search/", SearchView.as_view(), name="search"),
    path("new/", AlbumCreateView.as_view(), name="create"),
    path("list/", RedirectView.as_view(pattern_name="albums:all", permanent=True)),
    path("all/", AlbumListView.as_view(), name="all"),
    path("mine/", MyAlbumsView.as_view(), name="mine"),
    path(
        "my_gallery/", RedirectView.as_view(pattern_name="albums:mine", permanent=True)
    ),
    re_path(
        r"^album/\{?(?P<pk>\d+)\}?/$", AlbumDetailView.as_view(), name="detail"
    ),  # curly braces for Javascript url
    path("album/<int:pk>/edit/", AlbumUpdateView.as_view(), name="update"),
    path("album/<int:pk>/delete/", AlbumDeleteView.as_view(), name="delete"),
    path("album/<int:pk>/restore/", AlbumRestoreView.as_view(), name="restore"),
    path("album/<int:pk>/page/<int:page>/", AlbumDetailView.as_view(), name="detail"),
    path("album/<int:pk>/download/", AlbumDownloadView.as_view(), name="download"),
    path("photo/<int:pk>/", PhotoDetailView.as_view(), name="photo-detail"),
    path("photo/<int:pk>/edit/", PhotoUpdateView.as_view(), name="photo_update"),
    path("photo/<int:pk>/delete/", PhotoDeleteView.as_view(), name="photo_delete"),
    path("photo/<int:pk>/restore/", PhotoRestoreView.as_view(), name="photo_restore"),
    path("upload/", UploadView.as_view(), name="upload"),
    path("settings/", PreferencesUpdateView.as_view(), name="settings"),
    path(
        "preferences/",
        RedirectView.as_view(pattern_name="albums:settings", permanent=True),
    ),
]

src/brouwers/urls.py
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views.generic.base import RedirectView, TemplateView

from brouwers.anniversaries.views import TwentyYearsAnniversaryView
from brouwers.contact.views import ContactMessageCreateView

# FIXME: this breaks laziness
FORUM_URL = settings.PHPBB_URL
FORUM_URL = FORUM_URL[1:] if FORUM_URL.startswith("/") else FORUM_URL
FORUM_URL = FORUM_URL if FORUM_URL.endswith("/") else FORUM_URL + "/"


urlpatterns = (
    [
        # contact page because the live shop contact page email handling is horrible and gets
        # blocked by mail servers (including our own)
        path("winkel/contact", ContactMessageCreateView.as_view()),
        path("winkel/contact/", ContactMessageCreateView.as_view(), name="contact"),
        # normal application
        path("admin/rosetta/", include("rosetta.urls")),
        path("admin/", admin.site.urls),
        path("admin/", include("loginas.urls")),
        path("api/v1/", include("brouwers.api.urls", namespace="api")),
        # just a placeholder for the url
        path("", RedirectView.as_view(url="/index.php"), name="index"),
        path("20/", RedirectView.as_view(pattern_name="20-years-anniversary")),
        path(
            "20-jaar/",
            TwentyYearsAnniversaryView.as_view(),
            name="20-years-anniversary",
        ),
        path("albums/", include("brouwers.albums.urls", namespace="albums")),
        path("awards/", include("brouwers.awards.urls")),
        path(
            "brouwersdag/",
            RedirectView.as_view(permanent=True, pattern_name="brouwersdag:index"),
        ),
        path("forum_tools/", include("brouwers.forum_tools.urls")),
        path(FORUM_URL, include("brouwers.forum_tools.urls_phpbb", namespace="phpBB")),
        path(
            "group-builds/",
            include("brouwers.groupbuilds.urls", namespace="groupbuilds"),
        ),
        path(
            "kitreviews/", include("brouwers.kitreviews.urls", namespace="kitreviews")
        ),
        path("secret_santa/", TemplateView.as_view(template_name="santa_removed.html")),
        path("shirts/", TemplateView.as_view(template_name="shirts_removed.html")),
        path("builds/", include("brouwers.builds.urls", namespace="builds")),
        path(
            "modelbouwdag/sign-up/",
            RedirectView.as_view(
                permanent=True, pattern_name="brouwersdag:model-signup"
            ),
        ),
        path(
            "esm/",
            include("brouwers.brouwersdag.urls", namespace="brouwersdag"),
        ),
        path("i18n/", include("django.conf.urls.i18n")),
        path("nieuwe-winkel/", include("brouwers.shop.urls", namespace="shop")),
        path("", include("brouwers.users.urls", namespace="users")),
    ]
    + staticfiles_urlpatterns()
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)
)

if settings.DEBUG:
    urlpatterns += [
        path("404/", TemplateView.as_view(template_name="404.html")),
        path("dev/emails/", include("brouwers.emails.urls")),
    ]

if apps.is_installed("debug_toolbar"):
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

src/brouwers/albums/api/views.py
from django.db.models import Q

from rest_framework import parsers, permissions, status, viewsets
from rest_framework.decorators import action
from rest_framework.exceptions import ValidationError
from rest_framework.response import Response
from rest_framework.settings import api_settings

from ..models import Album, Photo, Preferences
from .filters import PhotoFilter
from .pagination import MyPhotoPagination, PhotoPagination
from .renderers import FineUploaderRenderer
from .serializers import (
    AlbumSerializer,
    ForumPhotoSerializer,
    PhotoSerializer,
    PreferencesSerializer,
    UploadPhotoSerializer,
)


class PhotoViewSet(viewsets.ModelViewSet):
    """
    View to handle HTML5 file uploads and photo manipulations such as
    rotating the photo.
    """

    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    parser_classes = api_settings.DEFAULT_PARSER_CLASSES + [parsers.FileUploadParser]
    queryset = Photo.objects.exclude(trash=True).select_related("user")
    serializer_class = PhotoSerializer
    filterset_class = PhotoFilter
    pagination_class = PhotoPagination

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return self.queryset.filter(
                Q(album__public=True) | Q(album__user=self.request.user)
            )
        return self.queryset.exclude(album__public=False)

    def get_renderers(self):
        if self.action == "create":
            return [FineUploaderRenderer()]
        return super().get_renderers()

    def get_serializer_class(self):
        if self.action == "create":
            return UploadPhotoSerializer
        return super().get_serializer_class()

    def create(self, request, *args, **kwargs):
        """
        Overwritten to comply with FineUploader's demands for the response.
        """
        serializer = self.get_serializer(data=request.data)
        if serializer.is_valid(raise_exception=True):
            serializer.save(user=self.request.user)
            headers = self.get_success_headers(serializer.data)
            response_data = serializer.data
            response_data.update({"success": True})
            return Response(response_data, status=status.HTTP_200_OK, headers=headers)
        return Response(
            {"success": False}, status=status.HTTP_400_BAD_REQUEST
        )  # pragma: no cover

    @action(detail=True, methods=["patch"])
    def rotate(self, request, *args, **kwargs):
        photo = self.get_object()
        direction = request.data.get("direction")
        if direction not in ["cw", "ccw"]:
            raise ValidationError("The direction must be set to 'cw' or 'ccw'")
        degrees = -90 if direction == "cw" else 90
        photo.rotate(degrees=degrees)
        serializer = self.get_serializer(self.get_object())
        return Response(serializer.data)


class PreferencesViewSet(viewsets.ReadOnlyModelViewSet):
    """
    Must always return the settings for the (logged in) user making the
    api request.
    """

    queryset = Preferences.objects.none()
    serializer_class = PreferencesSerializer
    pagination_class = None
    lookup_value_regex = "self"

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return Preferences.objects.filter(user=self.request.user)
        return super().get_queryset()

    def get_object(self):
        return Preferences.objects.get_for(self.request.user)

    def retrieve(self, request, *args, **kwargs):
        # from cache, or populates cache, thus already serialized
        return Response(self.get_object())


class MyAlbumsViewset(viewsets.ReadOnlyModelViewSet):
    queryset = Album.objects.none()
    permission_classes = (permissions.IsAuthenticated,)
    serializer_class = AlbumSerializer
    pagination_class = None

    def get_queryset(self):
        return Album.objects.for_user(self.request.user)


class MyPhotosViewset(viewsets.ReadOnlyModelViewSet):
    queryset = Photo.objects.none()
    permission_classes = (permissions.IsAuthenticated,)
    serializer_class = ForumPhotoSerializer
    filterset_class = PhotoFilter
    pagination_class = MyPhotoPagination

    def get_queryset(self):
        return Photo.objects.for_user(self.request.user).order_by("-uploaded")

    @action(detail=True, methods=["post"])
    def set_cover(self, request, *args, **kwargs):
        photo = self.get_object()
        photo.album.cover = photo
        photo.album.save()
        serializer = self.get_serializer(photo)
        return Response(serializer.data)

src/brouwers/albums/views/edit.py
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DeleteView, TemplateView, UpdateView

from brouwers.utils.views import LoginRequiredMixin

from ..forms import (
    AlbumForm,
    AlbumRestoreForm,
    PhotoForm,
    PhotoRestoreForm,
    PreferencesForm,
    UploadForm,
)
from ..models import Album, Photo, Preferences


class UploadView(LoginRequiredMixin, TemplateView):
    template_name = "albums/upload.html"

    def get(self, request, *args, **kwargs):
        if not request.user.album_set.exists():
            messages.warning(
                request, _("You need to create an album before you can upload photos")
            )
            return redirect(reverse("albums:create"))
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        kwargs["form"] = UploadForm(self.request, initial=self.request.GET)

        prefs = Preferences.objects.get_for(self.request.user)
        kwargs["upload_settings"] = {
            "endpoint": reverse("api:photo-list"),
            "albumDetail": reverse("albums:detail", kwargs={"pk": "{0}"}),
            "autoUpload": prefs["auto_start_uploading"],
        }
        return super().get_context_data(**kwargs)


class AlbumCreateView(LoginRequiredMixin, CreateView):
    model = Album
    form_class = AlbumForm
    template_name = "albums/album/create.html"
    success_url = reverse_lazy("albums:upload")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def get_initial(self):
        initial = super().get_initial()
        initial.setdefault(
            "title", "album {}".format(timezone.now().strftime("%d-%m-%Y"))
        )
        return initial

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        url = super().get_success_url()
        return f"{url}?album={self.object.id}"


class AlbumUpdateView(LoginRequiredMixin, UpdateView):
    model = Album
    form_class = AlbumForm
    template_name = "albums/album/update.html"
    success_url = reverse_lazy("albums:mine")

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(user=self.request.user)


class AlbumDeleteView(LoginRequiredMixin, DeleteView):
    model = Album
    template_name = "albums/album/confirm_delete.html"
    context_object_name = "album"
    success_url = reverse_lazy("albums:mine")

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        kwargs["photos"] = self.object.photo_set.filter(trash=False)
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.trash = True
        self.object.save()
        restore_url = reverse("albums:restore", kwargs={"pk": self.object.pk})
        messages.success(
            self.request,
            _('The album was deleted. <a href="{0}">Undo</a>').format(restore_url),
        )
        return redirect(success_url)


class AlbumRestoreView(AlbumUpdateView):
    form_class = AlbumRestoreForm
    success_url = reverse_lazy("albums:mine")
    template_name = "albums/album/restore.html"
    initial = {
        "trash": False,
    }


class PhotoSuccessURLMixin:
    def get_success_url(self):
        if not self.object.trash:
            return self.object.get_absolute_url()
        return reverse("albums:detail", kwargs={"pk": self.object.album.pk})


class PhotoUpdateView(PhotoSuccessURLMixin, LoginRequiredMixin, UpdateView):
    model = Photo
    form_class = PhotoForm
    template_name = "albums/photo/update.html"

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(user=self.request.user)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs


class PhotoDeleteView(LoginRequiredMixin, DeleteView):
    model = Photo
    template_name = "albums/photo/confirm_delete.html"
    context_object_name = "photo"

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(user=self.request.user, trash=False)

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.trash = True
        self.object.save()
        restore_url = reverse("albums:photo_restore", kwargs={"pk": self.object.pk})
        messages.success(
            self.request,
            _('The photo was deleted. <a href="{0}">Undo</a>').format(restore_url),
        )
        return redirect(success_url)

    def get_success_url(self):
        return reverse("albums:detail", kwargs={"pk": self.object.album.pk})


class PhotoRestoreView(PhotoSuccessURLMixin, LoginRequiredMixin, UpdateView):
    model = Photo
    form_class = PhotoRestoreForm
    template_name = "albums/photo/restore.html"
    initial = {
        "trash": False,
    }

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(user=self.request.user)


class PreferencesUpdateView(LoginRequiredMixin, UpdateView):
    model = Preferences
    form_class = PreferencesForm
    success_url = reverse_lazy("albums:index")

    def get_object(self, queryset=None):
        obj, _ = Preferences.objects.get_or_create(user=self.request.user)
        return obj

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, _("The changes have been saved."))
        return response

src/brouwers/albums/views/private.py
from collections import OrderedDict

from django.views.generic import TemplateView

from brouwers.utils.views import LoginRequiredMixin

from ..models import Album


class MyAlbumsView(LoginRequiredMixin, TemplateView):
    template_name = "albums/my_albums.html"

    def get_queryset(self, **extra_filters):
        albums = self.request.user.album_set.select_related("cover")
        return albums.filter(trash=False, **extra_filters)

    def get_shared_albums(self):
        user = self.request.user
        return Album.objects.select_related("cover").filter(
            albumgroup__users=user, trash=False
        )

    def get_my_shared_albums(self):
        user = self.request.user
        return (
            user.album_set.select_related("cover")
            .exclude(albumgroup__isnull=True)
            .exclude(trash=True)
        )

    def get_trashed_albums(self):
        user = self.request.user
        return (
            user.album_set.select_related("cover")
            .filter(trash=True)
            .order_by("-modified")
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tab_order = ["public", "private", "shared-with-me", "shared-by-me", "trashed"]
        _tab_content = {
            "public": self.get_queryset(public=True),
            "private": self.get_queryset(public=False),
            "shared-with-me": self.get_shared_albums(),
            "shared-by-me": self.get_my_shared_albums(),
            "trashed": self.get_trashed_albums(),
        }
        context["tabcontent"] = OrderedDict(
            sorted(_tab_content.items(), key=lambda t: tab_order.index(t[0]))
        )
        return context

src/brouwers/albums/templates/albums/includes/album_square.html
{% load static thumbnail i18n %}
<article class="col-sm-6 col-md-3 album-preview">
    <h3><a href="{{ album.get_absolute_url }}">{% if not album.trash %}{{ album.title }}{% else %}{{ album.clean_title }}{% endif %}</a></h3>
    <a href="{{ album.get_absolute_url }}" class="thumbnail">
        {% if album.get_cover.exists %}
            {% thumbnail album.cover.image "300x225" crop="center" as im %}
                <img src="{{ im.url }}" class="img-responsive">
            {% endthumbnail %}
        {% else %}
            <img src="{% static "images/thumb.png" %}" class="img-responsive">
        {% endif %}
    </a>
    {% if album.user == user %}
        <ul class="list-inline controls text-right">
            <li data-toggle="popover" data-content="{% trans 'Upload pictures' %}"
                data-trigger="hover" data-placement="top" data-container="body">
                <a href="{% url 'albums:upload' %}?album={{ album.pk }}"><i class="fa fa-fw fa-upload"></i></a>
            </li>
            <li data-toggle="popover" data-content="{% trans 'Edit album' %}"
                data-trigger="hover" data-placement="top" data-container="body">
                <a href="{% url 'albums:update' pk=album.pk %}"><i class="fa fa-fw fa-pencil-square-o"></i></a>
            </li>
            {% if not album.trash %}
            <li data-toggle="popover" data-content="{% trans 'Delete album' %}"
                data-trigger="hover" data-placement="top" data-container="body">
                <a href="{% url 'albums:delete' pk=album.pk %}"><i class="fa fa-fw fa-trash"></i></a>
            </li>
            {% else %}
            <li data-toggle="popover" data-content="{% trans 'Restore album' %}"
                data-trigger="hover" data-placement="top" data-container="body">
                <a href="{% url 'albums:restore' pk=album.pk %}"><i class="fa fa-fw fa-undo"></i></a>
            </li>
            {% endif %}
        </ul>
    {% endif %}
</article>

src/brouwers/albums/templates/albums/includes/photo_thumb.html
{% load thumbnail static i18n %}
<article class="col-sm-6 col-md-3" data-id="{{ photo.id }}">
    <a href="{{ photo.get_absolute_url }}" class="thumbnail album-photo{% if album.cover == photo %} cover{% endif %}" data-id="{{ photo.id }}">
        {% if photo.exists %}
            {% thumbnail photo.image "300x225" crop="center" as im %}
                <img src="{{ im.url }}" class="img-responsive">
            {% endthumbnail %}
        {% else %}
            <img src="{% static "images/thumb.png" %}" class="img-responsive">
        {% endif %}
    </a>
    {% if photo.user == user %}
        <ul class="list-inline controls text-right">
            <li data-toggle="popover" data-content="{% trans "Set as cover" %}" data-trigger="hover" data-placement="top" class="set-cover">
                <a href="#" data-action="set-cover"><i class="fa fa-fw fa-picture-o"></i></a>
            </li>
            <li data-toggle="popover" data-content="{% trans 'Edit photo' %}"
                data-trigger="hover" data-placement="top" data-container="body">
                <a href="{% url 'albums:photo_update' pk=photo.pk %}"><i class="fa fa-fw fa-pencil-square-o"></i></a>
            </li>
            {% if not photo.trash %}
            <li data-toggle="popover" data-content="{% trans 'Delete photo' %}"
                data-trigger="hover" data-placement="top" data-container="body">
                <a href="{% url 'albums:photo_delete' pk=photo.pk %}"><i class="fa fa-fw fa-trash"></i></a>
            </li>
            {% else %}
            <li data-toggle="popover" data-content="{% trans 'Restore photo' %}"
                data-trigger="hover" data-placement="top" data-container="body">
                <a href="{% url 'albums:photo_restore' pk=photo.pk %}"><i class="fa fa-fw fa-undo"></i></a>
            </li>
            {% endif %}
        </ul>
    {% endif %}
</article>

src/brouwers/albums/templates/albums/includes/search_form.html
{% load i18n %}
<form action="{% url 'albums:search' %}" method="get" class="search-form">
    <label for="search-input" class="sr-only">{% trans "Search terms" %}</label>
    <input id="search-input" class="form-control" name="q" placeholder="{% trans 'Topic or username' %}" value="{{ request.GET.q }}" >
    <button type="submit" class="btn button button--orange">{% trans "Search" %}</button>
</form>