src/brouwers/shop/api/urls.py
from django.urls import path

from .views import CartView, GetShippingCostsView, IdealBanksView

urlpatterns = [
    path("cart/", CartView.as_view(), name="cart-detail"),
    path("ideal_banks/", IdealBanksView.as_view(), name="ideal-banks"),
    path("shipping-costs/", GetShippingCostsView.as_view(), name="shipping-costs"),
]

src/brouwers/shop/urls.py
from django.urls import include, path
from django.views.generic import RedirectView

from .payments.paypal.views import (
    CancelView as PPCancelView,
    ReturnView as PPReturnView,
)
from .payments.sisow.views import PaymentCallbackView as SisowCallbackView
from .views import (
    CartDetailView,
    CheckoutView,
    ConfirmOrderView,
    DashboardView,
    IndexView,
    OrderDetailView,
    OrderListView,
    RouterView,
)

app_name = "shop"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    # set up redirects for old URLs Hanjo is used to :)
    path("achterdeur", RedirectView.as_view(pattern_name="shop:dashboard")),
    path("achterdeur/", RedirectView.as_view(pattern_name="shop:dashboard")),
    path(
        "backoffice/",
        include(
            [
                path("", DashboardView.as_view(), name="dashboard"),
                path("orders/", OrderListView.as_view(), name="order-list"),
                path(
                    "order/<slug:reference>/",
                    OrderDetailView.as_view(),
                    name="order-detail",
                ),
                path(
                    "orders/<slug:reference>/",
                    OrderDetailView.as_view(),
                    name="order-detail",
                ),
            ]
        ),
    ),
    path("cart/<int:pk>/", CartDetailView.as_view(), name="cart-detail"),
    # payments
    path(
        "payments/sisow/<int:pk>/callback/",
        SisowCallbackView.as_view(),
        name="sisow-payment-callback",
    ),
    path(
        "payments/paypal/<int:pk>/return", PPReturnView.as_view(), name="paypal-return"
    ),
    path(
        "payments/paypal/<int:pk>/cancel", PPCancelView.as_view(), name="paypal-cancel"
    ),
    # checkout flow
    path("checkout/confirm", ConfirmOrderView.as_view(), name="confirm-checkout"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("checkout/<path:path>", CheckoutView.as_view(), name="checkout"),
    # catch-all for catalogue routing - note that the individual
    # views are registered inside of RouterView
    path("<path:path>", RouterView.as_view(), name="catalogue"),
]

src/brouwers/urls.py
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views.generic.base import RedirectView, TemplateView

from brouwers.anniversaries.views import TwentyYearsAnniversaryView
from brouwers.contact.views import ContactMessageCreateView

# FIXME: this breaks laziness
FORUM_URL = settings.PHPBB_URL
FORUM_URL = FORUM_URL[1:] if FORUM_URL.startswith("/") else FORUM_URL
FORUM_URL = FORUM_URL if FORUM_URL.endswith("/") else FORUM_URL + "/"


urlpatterns = (
    [
        # contact page because the live shop contact page email handling is horrible and gets
        # blocked by mail servers (including our own)
        path("winkel/contact", ContactMessageCreateView.as_view()),
        path("winkel/contact/", ContactMessageCreateView.as_view(), name="contact"),
        # normal application
        path("admin/rosetta/", include("rosetta.urls")),
        path("admin/", admin.site.urls),
        path("admin/", include("loginas.urls")),
        path("api/v1/", include("brouwers.api.urls", namespace="api")),
        # just a placeholder for the url
        path("", RedirectView.as_view(url="/index.php"), name="index"),
        path("20/", RedirectView.as_view(pattern_name="20-years-anniversary")),
        path(
            "20-jaar/",
            TwentyYearsAnniversaryView.as_view(),
            name="20-years-anniversary",
        ),
        path("albums/", include("brouwers.albums.urls", namespace="albums")),
        path("awards/", include("brouwers.awards.urls")),
        path(
            "brouwersdag/",
            RedirectView.as_view(permanent=True, pattern_name="brouwersdag:index"),
        ),
        path("forum_tools/", include("brouwers.forum_tools.urls")),
        path(FORUM_URL, include("brouwers.forum_tools.urls_phpbb", namespace="phpBB")),
        path(
            "group-builds/",
            include("brouwers.groupbuilds.urls", namespace="groupbuilds"),
        ),
        path(
            "kitreviews/", include("brouwers.kitreviews.urls", namespace="kitreviews")
        ),
        path("secret_santa/", TemplateView.as_view(template_name="santa_removed.html")),
        path("shirts/", TemplateView.as_view(template_name="shirts_removed.html")),
        path("builds/", include("brouwers.builds.urls", namespace="builds")),
        path(
            "modelbouwdag/sign-up/",
            RedirectView.as_view(
                permanent=True, pattern_name="brouwersdag:model-signup"
            ),
        ),
        path(
            "esm/",
            include("brouwers.brouwersdag.urls", namespace="brouwersdag"),
        ),
        path("i18n/", include("django.conf.urls.i18n")),
        path("nieuwe-winkel/", include("brouwers.shop.urls", namespace="shop")),
        path("", include("brouwers.users.urls", namespace="users")),
    ]
    + staticfiles_urlpatterns()
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)
)

if settings.DEBUG:
    urlpatterns += [
        path("404/", TemplateView.as_view(template_name="404.html")),
        path("dev/emails/", include("brouwers.emails.urls")),
    ]

if apps.is_installed("debug_toolbar"):
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

src/brouwers/shop/models/cart.py
from __future__ import annotations

from decimal import Decimal
from typing import ClassVar

from django.conf import settings
from django.core.serializers.json import DjangoJSONEncoder
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from ..constants import TWO_DIGITS, CartStatuses
from ..managers import CartQuerySet


class Cart(models.Model):
    id: int
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="carts",
    )
    status = models.CharField(
        _("status"),
        max_length=50,
        choices=CartStatuses.choices,
        default=CartStatuses.open,
    )
    snapshot_data = models.JSONField(
        _("snapshot data"),
        encoder=DjangoJSONEncoder,
        help_text=_("Snapshot of order information with frozen prices."),
        null=True,
    )

    objects: ClassVar[CartQuerySet] = CartQuerySet.as_manager()  # type: ignore
    products: models.QuerySet[CartProduct]

    class Meta:
        verbose_name = _("cart")
        verbose_name_plural = _("carts")

    def get_absolute_url(self):
        return reverse("shop:cart-detail", kwargs={"pk": self.pk})

    @property
    def total(self) -> Decimal:
        """
        Total price of all the products in the cart
        """
        return sum((product.total for product in self.products.all()), start=Decimal(0))

    @property
    def weight(self) -> int:
        """
        Calculate the weight in grams.
        """
        return int(sum(product.weight for product in self.products.all()))

    def save_snapshot(self) -> None:
        """
        Freeze all the cart product information for archiving purposes.

        This prevents historic orders and their prices/totals being mutated when product
        prices eventually are updated/indexed, or even completely removed.

        TODO: include reduction/benefits information
        """
        data = {"products": [], "total": self.total}
        for cart_product in self.products.all():
            data["products"].append(
                {
                    "id": cart_product.product.id,
                    "name": str(cart_product.product),
                    "amount": cart_product.amount,
                    "price": cart_product.product.price,
                    "vat": cart_product.product.vat,
                    "total": cart_product.total,
                }
            )

        self.snapshot_data = data
        self.save(update_fields=["snapshot_data"])


class CartProduct(models.Model):
    product = models.ForeignKey(
        "Product",
        related_name="cart_products",
        on_delete=models.CASCADE,
    )
    cart = models.ForeignKey("Cart", related_name="products", on_delete=models.CASCADE)
    amount = models.PositiveIntegerField(_("amount"), default=1)

    class Meta:
        verbose_name = _("cart product")
        verbose_name_plural = _("cart products")

    def __str__(self):
        return self.product.name or self.product.name_nl

    @property
    def total(self) -> Decimal:
        """
        Total price for the amount of products
        """
        return (self.product.price * self.amount).quantize(TWO_DIGITS)

    @property
    def weight(self) -> Decimal:
        """
        Calculate the weight in grams.
        """
        return self.product.weight_in_grams * self.amount

src/brouwers/shop/models/orders.py
from typing import TYPE_CHECKING

from django.conf import settings
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from furl import furl

from brouwers.general.fields import CountryField

from ..constants import DeliveryMethods, OrderStatuses, PaymentStatuses
from .utils import get_random_reference

if TYPE_CHECKING:
    from .payments import Payment


class Address(models.Model):
    street = models.CharField(_("street name"), max_length=255)
    number = models.CharField(_("house number"), max_length=30, blank=True)
    postal_code = models.CharField(_("postal code"), max_length=50)
    city = models.CharField(_("city"), max_length=255)
    country = CountryField()

    # company details
    company = models.CharField(_("company"), max_length=255, blank=True)
    chamber_of_commerce = models.CharField(
        _("chamber of commerce number"), max_length=50, blank=True
    )

    class Meta:
        verbose_name = _("address")
        verbose_name_plural = _("addresses")

    def __str__(self):
        bits = [
            f"{self.street} {self.number}".strip(),
            self.postal_code,
            self.city,
            self.country,
        ]
        return ", ".join(bits)


def get_order_reference():
    """
    Generate a random but unique reference.
    """
    MAX_ATTEMPTS = 100  # ensure we have finite loops (while is evil)
    iterations = 0

    for _ in range(MAX_ATTEMPTS):  # noqa: F402
        iterations += 1
        reference = get_random_reference()
        exists = Order.objects.only("pk").filter(reference=reference).exists()
        if exists is False:
            return reference

    # loop ran all the way to the end without finding unused reference
    # (otherwise it would have returned)
    raise RuntimeError(
        f"Could not get a unused reference after {iterations} attempts!"
    )  # pragma: no cover


class Order(models.Model):
    cart = models.OneToOneField(
        "Cart", on_delete=models.PROTECT, verbose_name=_("shopping cart")
    )
    status = models.CharField(_("status"), max_length=50, choices=OrderStatuses.choices)
    reference = models.CharField(
        _("reference"),
        max_length=16,
        unique=True,
        default=get_order_reference,
        help_text=_("A unique order reference"),
    )
    # TODO: add django-privates and field for invoices

    # personal details
    first_name = models.CharField(_("first name"), max_length=255)
    last_name = models.CharField(_("last name"), max_length=255, blank=True)
    email = models.EmailField(_("email"))
    phone = models.CharField(_("phone number"), max_length=100, blank=True)

    # addresses
    delivery_method = models.CharField(
        _("delivery method"),
        max_length=20,
        choices=DeliveryMethods.choices,
    )
    delivery_address = models.OneToOneField(
        "Address",
        on_delete=models.PROTECT,
        related_name="delivery_order",
        help_text=_("Address for delivery"),
        blank=True,
        null=True,
    )
    invoice_address = models.OneToOneField(
        "Address",
        on_delete=models.SET_NULL,
        related_name="invoice_order",
        blank=True,
        null=True,
    )

    # metadata
    created = models.DateTimeField(_("created"), auto_now_add=True)
    modified = models.DateTimeField(_("modified"), auto_now=True)
    language = models.CharField(
        _("language"), max_length=10, default="nl", choices=settings.LANGUAGES
    )

    shipping_costs = models.DecimalField(
        _("shipping costs"),
        decimal_places=2,
        max_digits=6,
        blank=True,
        null=True,
    )

    payment: "Payment"

    class Meta:
        verbose_name = _("order")
        verbose_name_plural = _("orders")
        constraints = [
            models.CheckConstraint(
                name="delivery_address_when_shipping",
                check=(
                    Q(
                        delivery_method=DeliveryMethods.mail,
                        delivery_address__isnull=False,
                    )
                    | ~Q(delivery_method=DeliveryMethods.mail)
                ),
                violation_error_message=_(
                    "A delivery address must be specified when deliverying via mail."
                ),
            )
        ]

    def __str__(self):
        return _("Order {pk}").format(pk=self.pk)

    @property
    def is_actionable(self) -> bool:
        if self.payment.status != PaymentStatuses.completed:
            return False

        if self.status == OrderStatuses.received:
            return True

        return False

    def get_full_name(self) -> str:
        bits = [self.first_name, self.last_name]
        return " ".join(bits).strip()

    def get_confirmation_link(self) -> str:
        path = reverse("shop:checkout", kwargs={"path": "confirmation"})
        return furl(path).set({"orderId": self.pk}).url

src/brouwers/shop/api/views.py
from django.utils.formats import number_format

from rest_framework import serializers, views
from rest_framework.request import Request
from rest_framework.response import Response

from brouwers.general.constants import CountryChoices

from ..constants import CART_SESSION_KEY
from ..models import Cart, ShippingCost
from ..payments.sisow.service import get_ideal_banks
from .serializers import CartSerializer, iDealBankSerializer


class IdealBanksView(views.APIView):
    def get(self, request):
        serializer = iDealBankSerializer(
            instance=get_ideal_banks(),
            many=True,
            context={"request": request},
        )
        return Response(serializer.data)


class CartView(views.APIView):
    def get(self, request):
        cart = Cart.objects.open().for_request(request).last()

        if cart is None:
            if request.user.is_authenticated:
                cart = Cart.objects.create(user=request.user)
            else:
                cart = Cart.objects.create()
            request.session[CART_SESSION_KEY] = cart.id

        serializer = CartSerializer(instance=cart)
        return Response(serializer.data)


class GetShippingCostsView(views.APIView):
    def get(self, request: Request):
        cart_id: str | None = request.GET.get("cart_id")
        match cart_id:
            case None:
                raise serializers.ValidationError(
                    {"cart_id": "cart_id query param is required."}, code="required"
                )
            case str() if cart_id.isdigit():
                cart = (
                    Cart.objects.open().for_request(request).filter(pk=cart_id).first()
                )
            case _:
                raise serializers.ValidationError({"cart_id": "Invalid cart ID."})
        if cart is None:
            raise serializers.ValidationError({"cart_id": "Invalid cart ID."})
        assert isinstance(cart, Cart)

        try:
            country = CountryChoices(request.GET.get("country"))
        except ValueError:
            raise serializers.ValidationError({"country": "Invalid country."}) from None

        # now the cart and country have been validated, calculate the price
        total_weight_in_grams = cart.weight

        # TODO
        price = ShippingCost.objects.get_price(
            country=country, weight=total_weight_in_grams
        )
        assert price is not None

        if total_weight_in_grams < 1000:
            number = number_format(total_weight_in_grams)
            formatted_weight = f"{number} g"
        else:
            number = number_format(total_weight_in_grams / 1000)
            formatted_weight = f"{number} kg"

        return Response(
            {
                "weight": formatted_weight,
                "price": str(price),
            }
        )

src/brouwers/shop/views/mixins.py
from django.contrib.auth.mixins import PermissionRequiredMixin

from brouwers.utils.tests import is_testing


class TestPermissionsRequiredMixin(PermissionRequiredMixin):
    permission_required = "shop.add_product"
    raise_exception = True

    def has_permission(self):  # pragma: no cover
        if is_testing():
            return True
        return super().has_permission()

src/brouwers/shop/templates/shop/backoffice/base.html
{% extends "base.html" %}
{% load i18n static brouwers %}

{% block nav-top %}
<div class="navbar navbar-default navbar--center-logo navbar--no-margin" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">{% trans "Toggle navigation" %}</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'index' %}">
                <img src="{% static 'images/logo/logo_modelbrouwers.png' %}" alt="{% trans 'Back to the Modelbrouwers.nl homepage' %}">
            </a>
        </div>

        {% url 'shop:order-list' as url_order_list %}

        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="{% if request.path|startswith:url_order_list %}active{% endif %}">
                    <a href="{{ url_order_list }}">
                        {% trans "Order list" %}
                    </a>
                </li>
                <li>
                    <a href="{% url 'admin:shop_product_changelist' %}">
                        {% trans "Manage products" %}
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block sub-nav %}{% endblock %}

src/brouwers/shop/templates/shop/backoffice/dashboard.html
{% extends "base.html" %}
{% load i18n shop %}

{% block title %} {% trans "Shop backoffice | Dashboard" %}{% endblock %}

{% block body-class %}shop-backoffice{% endblock body-class %}

{% block eye-catcher %}
    <header class="container-fluid eye-catcher">
        <div class="container">
            <h1>
                {% trans "Shop dashboard" %}
                <i class="pull-right fa fa-bar-chart-o fa-2x"></i>
            </h1>

            <p>{% blocktrans trimmed %}
                Quick overview to manage the shop.
            {% endblocktrans %}</p>
        </div>
    </header>
{% endblock %}

{% block content %}

<div class="dashboard">

    <a class="dashboard-tile" href="{% url 'shop:order-list' %}">
        <i class="dashboard-tile__icon fa fa-shopping-bag fa-4x"></i>
        <span class="dashboard-tile__label">
            {% blocktrans count new_order_count=new_order_count trimmed %}
                Orders (1 new)
            {% plural %}
                Orders ({{ new_order_count }} new)
            {% endblocktrans %}
        </span>
    </a>

    <a class="dashboard-tile" href="{% url 'admin:shop_product_changelist' %}">
        <i class="dashboard-tile__icon fa fa-shopping-cart fa-4x"></i>
        <span class="dashboard-tile__label">
            {% trans "Manage products" %}
        </span>
    </a>

</div>

{% endblock %}

src/brouwers/shop/templates/shop/backoffice/order_detail.html
{% extends "shop/backoffice/base.html" %}
{% load i18n shop %}

{% block title %}
{% blocktrans with ref=order.reference %}Shop backoffice | Order {{ ref }}{% endblocktrans %}
{% endblock %}

{% block body-class %}shop-backoffice{% endblock body-class %}

{% block eye-catcher %}
    <div class="container">
        <header>
            <h1>
                {{ order.reference }}
                <small title="{% trans 'Current status' %}">{{ order.get_status_display }}</small>
            </h1>
        </header>
    </div>
{% endblock %}

{% block content %}
<form class="order-detail" action="." method="post">
    {% csrf_token %}

    <section class="order-detail__status">
        <div class="order-detail__form">
            <div class="form-group">
                <label for="{{ form.status.id_for_label }}">
                    {% trans "Change status to" %}:
                </label>
                {{ form.status }}
            </div>
        </div>

        {% with payment=order.payment %}

            <heading class="order-detail__heading">
                <h3> {% trans "Payment" %} </h3>

                {% if payment %}
                    <div class="order-detail__heading-badges">

                        {% with status=order.payment.status %}
                            <span class="
                                order-detail__heading-badge
                                order-detail__heading-badge--{% if status == 'completed' %}success{% elif status == 'cancelled' %}danger{% else %}neutral{% endif %}
                            ">
                                {{ order.payment.format_amount }}
                            </span>
                        {% endwith %}

                        <span class="order-detail__heading-badge">
                            {{ order.payment.payment_method.name }}
                        </span>

                    </div>
                {% endif %}

            </heading>

            {% if payment %}
                <div class="order-detail__form">
                    <div class="form-group">
                        {{ form.payment_status.label_tag }}
                        {{ form.payment_status }}
                    </div>
                </div>
            {% else %}
                <p>{% trans "There is no payment information for this order." %}</p>
            {% endif %}

        {% endwith %}

    </section>

    <section class="order-detail__products">
        <h2>
            {% trans "Products" %}
            <span class="badge">{{ num_products }}</span>
        </h2>

        <ul class="product-list">

            <li class="product-list__product product-list__product--headings">
                <span aria-hidden="true">&nbsp;</span>
                <span class="product-list__product-link">{% trans "Product" %}</span>
                <span class="product-list__product-model">{% trans "Model" %}</span>
                <span class="product-list__product-amount">{% trans "Amount" %}</span>
            </li>

            {% for cart_product in order.cart.products.all %}
                {% with product=cart_product.product name=cart_product.product.name %}
                <li class="product-list__product">
                    <img
                        src="{{ cart_product.product.get_image_url }}"
                        class="img-responsive"
                        alt="{% blocktrans %}Product image for '{{ name }}' {% endblocktrans %}"
                    >
                    <a
                        href="{% url 'admin:shop_product_change' product.pk %}"
                        class="product-list__product-link"
                    >{{ name }}</a>
                    <span class="product-list__product-model">
                        {{ product.model_name|default:_('-') }}
                    </span>
                    <span class="product-list__product-amount">{{ cart_product.amount }}</span>
                </li>
                {% endwith %}
            {% endfor %}
        </ul>

    </section>

    <div class="order-detail__customer">

        <section>
            <h2>{% trans "Customer" %}</h2>
            <strong>{{ order.get_full_name }}</strong>

            <p>
                <a href="mailto:{{ order.email }}">{{ order.email }}</a>
                {% if order.phone %}
                    <br>
                    <a href="tel:{{ order.phone }}">{{ order.phone }}</a>
                {% endif %}
            </p>
        </section>

        <section>
            <h3>{% trans "Delivery" %}</h3>
            <p>{{ order.get_delivery_method_display }}</p>

            <strong>{% trans "Delivery address" %}</strong>
            {% include "shop/includes/address.html" with address=order.delivery_address %}
        </section>

        {% if order.delivery_method == DeliveryMethods.mail %}

        <section>
            <h3>{% trans "Invoice address" %}</h3>
            {% if not order.invoice_address %}
                <p>{% trans "Same as delivery address." %}</p>
            {% else %}

                {% include "shop/includes/address.html" with address=order.invoice_address %}
            {% endif %}
        </section>
        {% endif %}

        <aside class="order-detail__meta">
            <h2 class="h3">{% trans "Order details" %}</h2>

            <ul>
                <li>
                    {% blocktrans with since=order.created|timesince isodate=order.created.isoformat title=order.created %}
                        Created:
                        <time datetime="{{ isodate }}" title="{{ title }}">
                            {{ since }} ago
                        </time>
                    {% endblocktrans %}
                </li>
                <li>
                    {% blocktrans with since=order.modified|timesince isodate=order.modified.isoformat title=order.modified %}
                        Last modified:
                        <time datetime="{{ isodate }}" title="{{ title }}">
                            {{ since }} ago
                        </time>
                    {% endblocktrans %}
                </li>
                <li>
                    {% blocktrans with lang=order.get_language_display %}
                        Language: {{ lang }}
                    {% endblocktrans %}
                </li>
            </ul>
        </aside>
    </div>

    <div class="order-detail__button-row">
        <div class="checkbox">
            <label>
                {{ form.send_email_notification }}
                {{ form.send_email_notification.label }}
            </label>
        </div>
        <button type="submit" class="btn btn-sm button button--orange">
            {% trans "Save changes" %}
        </button>
    </div>
</form>
{% endblock %}

src/brouwers/shop/templates/shop/backoffice/order_list.html
{% extends "shop/backoffice/base.html" %}
{% load i18n %}

{% block title %} {% trans "Shop backoffice | Orders" %}{% endblock %}

{% block body-class %}shop-backoffice{% endblock body-class %}

{% block eye-catcher %}
    <header class="container-fluid eye-catcher">
        <div class="container">
            <h1>
                {% trans "Orders" %}
                <i class="pull-right fa fa-shopping-bag fa-2x"></i>
            </h1>

            <p>{% blocktrans trimmed %}
                Overview of all orders, sorted by most recently placed first.
            {% endblocktrans %}</p>
        </div>
    </header>
{% endblock %}

{% block content %}
    <ol class="order-list">
        {% for order in orders %}
            {% url 'shop:order-detail' reference=order.reference as detail_url %}
            <li class="order-summary {% if order.status == 'received' %}order-summary--new{% endif %} {% if order.is_actionable %}order-summary--actionable{% endif %}">

                <heading class="order-summary__heading">
                    <h2 class="order-summary__reference">
                        <a href="{{ detail_url }}" class="order-summary__reference-link" title="{% trans 'Order number' %}">
                            {{ order.reference }}
                        </a>
                    </h2>

                    {% if order.payment %}
                        <div class="order-summary__price">
                            {{ order.payment.format_amount }}
                        </div>
                    {% endif %}
                </heading>

                <span class="order-summary__name" title="{% trans 'Customer' %}">
                    {{ order.get_full_name }}
                </span>

                <div class="order-summary__metadata">
                    <div class="key-value key-value--stretch-mobile">
                        <div class="key-value__label">
                            {% trans "Payment status" %}
                        </div>
                        <div class="key-value__text">
                            {% if order.payment %}
                                {{ order.payment.get_status_display }}
                            {% else %}
                                {% trans "No payment information." %}
                            {% endif %}
                        </div>
                    </div>

                    <div class="key-value key-value--stretch-mobile">
                        <div class="key-value__label">
                            {% trans "Order status" %}
                        </div>
                        <div class="key-value__text">
                            {{ order.get_status_display }}
                        </div>
                    </div>

                    <div class="key-value key-value--stretch-mobile">
                        <div class="key-value__label">
                            {% trans 'Placed' %}
                        </div>
                        <div class="key-value__text">
                            <time datetime="{{ order.created.isoformat }}">
                            {% blocktrans with since=order.created|timesince trimmed %}
                                {{ since }} ago
                            {% endblocktrans %}
                            </time>
                        </div>
                    </div>
                </div>

                <div class="text-right">
                    <a href="{{ detail_url }}" class="button button--light-blue order-summary__detail-link">
                        {% trans "Manage order" %}
                        {% if order.is_actionable %}
                            &nbsp;
                            <i class="fa fa-exclamation" title="{% trans "Order is actionable" %}"></i>
                        {% endif %}
                    </a>
                </div>
            </li>
        {% endfor %}
    </section>
    {% include "includes/pagination.html" %}
{% endblock %}