src/brouwers/kitreviews/urls.py
from django.urls import path

from .views import (
    AddReview,
    IndexView,
    KitReviewDetail,
    KitSearchView,
    LegacyRedirectView,
    ReviewListView,
)

app_name = "kitreviews"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("add/", AddReview.as_view(), name="add_review"),
    path("search/", KitSearchView.as_view(), name="find_kit"),
    path("kit/<slug>/reviews/", ReviewListView.as_view(), name="review-list"),
    path(
        "kit/<slug>/reviews/<int:pk>/", KitReviewDetail.as_view(), name="review-detail"
    ),
    path("kit/<slug>/reviews/add/", AddReview.as_view(), name="review-add"),
    # legacy urls
    path("kitreview_search_result_review.php", LegacyRedirectView.as_view()),
]

src/brouwers/urls.py
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views.generic.base import RedirectView, TemplateView

from brouwers.anniversaries.views import TwentyYearsAnniversaryView
from brouwers.contact.views import ContactMessageCreateView

# FIXME: this breaks laziness
FORUM_URL = settings.PHPBB_URL
FORUM_URL = FORUM_URL[1:] if FORUM_URL.startswith("/") else FORUM_URL
FORUM_URL = FORUM_URL if FORUM_URL.endswith("/") else FORUM_URL + "/"


urlpatterns = (
    [
        # contact page because the live shop contact page email handling is horrible and gets
        # blocked by mail servers (including our own)
        path("winkel/contact", ContactMessageCreateView.as_view()),
        path("winkel/contact/", ContactMessageCreateView.as_view(), name="contact"),
        # normal application
        path("admin/rosetta/", include("rosetta.urls")),
        path("admin/", admin.site.urls),
        path("admin/", include("loginas.urls")),
        path("api/v1/", include("brouwers.api.urls", namespace="api")),
        # just a placeholder for the url
        path("", RedirectView.as_view(url="/index.php"), name="index"),
        path("20/", RedirectView.as_view(pattern_name="20-years-anniversary")),
        path(
            "20-jaar/",
            TwentyYearsAnniversaryView.as_view(),
            name="20-years-anniversary",
        ),
        path("albums/", include("brouwers.albums.urls", namespace="albums")),
        path("awards/", include("brouwers.awards.urls")),
        path(
            "brouwersdag/",
            RedirectView.as_view(permanent=True, pattern_name="brouwersdag:index"),
        ),
        path("forum_tools/", include("brouwers.forum_tools.urls")),
        path(FORUM_URL, include("brouwers.forum_tools.urls_phpbb", namespace="phpBB")),
        path(
            "group-builds/",
            include("brouwers.groupbuilds.urls", namespace="groupbuilds"),
        ),
        path(
            "kitreviews/", include("brouwers.kitreviews.urls", namespace="kitreviews")
        ),
        path("secret_santa/", TemplateView.as_view(template_name="santa_removed.html")),
        path("shirts/", TemplateView.as_view(template_name="shirts_removed.html")),
        path("builds/", include("brouwers.builds.urls", namespace="builds")),
        path(
            "modelbouwdag/sign-up/",
            RedirectView.as_view(
                permanent=True, pattern_name="brouwersdag:model-signup"
            ),
        ),
        path(
            "esm/",
            include("brouwers.brouwersdag.urls", namespace="brouwersdag"),
        ),
        path("i18n/", include("django.conf.urls.i18n")),
        path("nieuwe-winkel/", include("brouwers.shop.urls", namespace="shop")),
        path("", include("brouwers.users.urls", namespace="users")),
    ]
    + staticfiles_urlpatterns()
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)
)

if settings.DEBUG:
    urlpatterns += [
        path("404/", TemplateView.as_view(template_name="404.html")),
        path("dev/emails/", include("brouwers.emails.urls")),
    ]

if apps.is_installed("debug_toolbar"):
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

src/brouwers/kitreviews/models.py
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from brouwers.albums.models import Album
from brouwers.forum_tools.fields import ForumToolsIDField
from brouwers.kits.fields import KitForeignKey

from .constants import VoteTypes
from .managers import KitReviewQuerySet

DEFAULT_RATING = 50
MAX_RATING = 100
MIN_RATING = 0


class KitReview(models.Model):
    """
    Model holding the review information for a model kit
    """

    legacy_id = models.IntegerField(blank=True, null=True, db_index=True)
    model_kit = KitForeignKey(on_delete=models.CASCADE, verbose_name=_("model kit"))
    raw_text = models.TextField(
        _("review"),
        help_text=_("The content of the review. Please be detailed!"),
    )
    properties = models.ManyToManyField(
        "KitReviewProperty",
        blank=True,
        through="KitReviewPropertyRating",
        related_name="+",
    )

    # linking to extra information
    album = models.ForeignKey(
        Album, verbose_name=_("album"), blank=True, null=True, on_delete=models.SET_NULL
    )
    topic = ForumToolsIDField(
        _("topic"),
        type="topic",
        blank=True,
        null=True,
        help_text=_("ID of the topic on Modelbrouwers."),
    )
    external_topic_url = models.URLField(
        _("external topic url"),
        blank=True,
        help_text=_("URL to the topic not hosted on Modelbrouwers"),
    )

    # some privacy settings...
    show_real_name = models.BooleanField(
        _("show real name?"),
        default=True,
        help_text=_(
            "Checking this option will display your real name as reviewer. Uncheck to use your nickname."
        ),
    )

    # internal information
    reviewer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    submitted_on = models.DateTimeField(auto_now_add=True)
    last_edited_on = models.DateTimeField(auto_now=True)

    is_reviewed = models.BooleanField(_("is reviewed?"), default=False)

    objects = KitReviewQuerySet.as_manager()

    class Meta:
        verbose_name = _("kit review")
        verbose_name_plural = _("kit reviews")

    def __str__(self):
        return _("Review: %(kit)s by %(user)s") % {
            "kit": self.model_kit.name,
            "user": self.reviewer.username,
        }

    def get_absolute_url(self):
        return reverse(
            "kitreviews:review-detail",
            kwargs={"pk": self.pk, "slug": self.model_kit.slug},
        )

    @property
    def topic_url(self):
        if self.topic_id and self.topic:
            return self.topic.get_absolute_url()
        if self.external_topic_url:
            return self.external_topic_url
        return None

    @property
    def reviewer_name(self):
        if self.show_real_name:
            return self.reviewer.get_full_name()
        return self.reviewer.username


class KitReviewVote(models.Model):
    """
    Model holding the votes for kit reviews, showing the quality of the review
    """

    kit_review = models.ForeignKey(KitReview, on_delete=models.CASCADE)
    vote = models.CharField(
        _("vote"), max_length=1, db_index=True, choices=VoteTypes.choices
    )
    voter = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("kit review vote")
        verbose_name_plural = _("kit review votes")
        unique_together = (("kit_review", "voter"),)

    def __str__(self):
        return _("Vote for review by %(review_submitter)s") % {
            "review_submitter": self.kit_review.reviewer.username
        }


class KitReviewProperty(models.Model):
    """
    Model containing the possible rating properties for a review
    """

    name = models.CharField(_("name"), max_length=255)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name = _("kit review property")
        verbose_name_plural = _("kit review properties")

    def __str__(self):
        return self.name


class KitReviewPropertyRating(models.Model):
    """
    Represents properties for a kit review rated on a scale from MIN_RATING to MAX_RATING
    """

    kit_review = models.ForeignKey(
        "KitReview", related_name="ratings", on_delete=models.CASCADE
    )
    prop = models.ForeignKey("KitReviewProperty", on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(
        _("rating"),
        default=DEFAULT_RATING,
        validators=[MinValueValidator(MIN_RATING), MaxValueValidator(MAX_RATING)],
    )

    class Meta:
        verbose_name = _("kit review property rating")
        verbose_name_plural = _("kit review property ratings")

src/brouwers/kitreviews/forms.py
from collections import OrderedDict

from django import forms
from django.db.models import Q
from django.utils.translation import gettext_lazy as _

from brouwers.forum_tools.models import Topic
from brouwers.kits.models import Brand, ModelKit, Scale
from brouwers.kits.widgets import ModelKitSelect
from brouwers.utils.forms import AlwaysChangedModelForm
from brouwers.utils.widgets import RangeInput

from .models import MAX_RATING, KitReview, KitReviewPropertyRating


class FindModelKitForm(forms.Form):
    brand = forms.ModelChoiceField(
        queryset=Brand.objects.all(), label=_("Brand"), required=False
    )
    kit_number = forms.CharField(label=_("Kit number"), required=False)
    kit_name = forms.CharField(label=_("Kit name"), required=False)
    scale = forms.ModelChoiceField(
        queryset=Scale.objects.all(), label=_("Scale"), required=False
    )

    def find_kits(self):
        results = ModelKit.objects.select_related("brand", "scale")

        brand = self.cleaned_data["brand"]
        if brand:
            results = results.filter(brand_id=brand.id)

        kit_number = self.cleaned_data["kit_number"]
        if kit_number:
            results = results.filter(kit_number__icontains=kit_number)

        kit_name = self.cleaned_data["kit_name"]
        if kit_name:
            name_parts = kit_name.split(" ")
            # order doesn't matter, just find the kits with names that have all
            # the search terms
            q_list = [Q(name__icontains=part) for part in name_parts]
            results = results.filter(*q_list)

        scale = self.cleaned_data["scale"]
        if scale:
            results = results.filter(scale_id=scale.id)
        return results


class KitReviewForm(forms.ModelForm):
    topic = forms.ModelChoiceField(queryset=Topic.objects.none(), required=False)

    class Meta:
        model = KitReview
        fields = [
            "model_kit",
            "raw_text",
            "album",
            "topic",
            "external_topic_url",
            "show_real_name",
        ]
        widgets = {
            "model_kit": ModelKitSelect,
            "raw_text": forms.Textarea(attrs={"rows": 10}),
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        # limit album selection to own albums
        # TODO: include group albums and public albums...
        self.fields["model_kit"].queryset = self.fields[
            "model_kit"
        ].queryset.select_related("brand")
        self.fields["album"].queryset = self.user.album_set.filter(trash=False)

        forum_user = self.user.forumuser
        if forum_user is not None:
            topics = (
                Topic.objects.select_related("forum")
                .filter(author=forum_user)
                .order_by("forum__forum_name", "-last_post_time")
            )

            choices = OrderedDict()
            choices[""] = "-------"
            for topic in topics:
                if topic.forum.forum_name not in choices:
                    choices[topic.forum.forum_name] = []
                choices[topic.forum.forum_name].append((topic.pk, topic.topic_title))
            self.fields["topic"].choices = choices.items()
            self.fields["topic"].queryset = topics

    def save(self, *args, **kwargs):
        self.instance.reviewer = self.user
        return super().save(*args, **kwargs)


class KitReviewPropertyRatingForm(AlwaysChangedModelForm):
    class Meta:
        model = KitReviewPropertyRating
        fields = ("id", "prop", "rating")
        widgets = {"rating": RangeInput(attrs={"max": MAX_RATING})}

src/brouwers/kitreviews/views.py
from django.db.models import Count, Prefetch
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, FormView, ListView, RedirectView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import FormMixin

from extra_views import CreateWithInlinesView, InlineFormSetFactory, NamedFormsetsMixin

from brouwers.kits.models import ModelKit
from brouwers.utils.views import LoginRequiredMixin

from .forms import FindModelKitForm, KitReviewForm, KitReviewPropertyRatingForm
from .models import KitReview, KitReviewProperty, KitReviewPropertyRating


class IndexView(FormMixin, ListView):
    queryset = (
        KitReview.objects.select_related("reviewer", "model_kit")
        .annotate_mean_rating()
        .order_by("-submitted_on")[:5]
    )
    context_object_name = "reviews"
    template_name = "kitreviews/index.html"
    form_class = FindModelKitForm


class ReviewPropertyRatingInline(InlineFormSetFactory):
    model = KitReviewPropertyRating
    form_class = KitReviewPropertyRatingForm

    @property
    def num_properties(self):
        if not hasattr(self, "_num_properties"):
            self._num_properties = KitReviewProperty.objects.count()
        return self._num_properties

    def get_factory_kwargs(self):
        kwargs = super().get_factory_kwargs()
        kwargs.update(
            {
                "extra": self.num_properties,
                "min_num": self.num_properties,
                "max_num": self.num_properties,
            }
        )
        return kwargs

    def get_initial(self):
        return [{"prop": prop} for prop in KitReviewProperty.objects.all()]


class AddReview(LoginRequiredMixin, NamedFormsetsMixin, CreateWithInlinesView):
    model = KitReview
    template_name = "kitreviews/add_review.html"
    form_class = KitReviewForm
    inlines = [ReviewPropertyRatingInline]
    inlines_names = ["properties"]

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def get_initial(self):
        initial = super().get_initial()
        if self.kwargs.get("slug"):
            initial["model_kit"] = get_object_or_404(ModelKit, slug=self.kwargs["slug"])
        return initial


class KitSearchView(FormView):
    template_name = "kitreviews/find_kit.html"
    form_class = FindModelKitForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if "data" not in kwargs:
            kwargs["data"] = self.request.GET
        return kwargs

    def get(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        return self.render_to_response(self.get_context_data())

    def form_valid(self, form):
        kits = form.find_kits()
        kits = kits.annotate(num_reviews=Count("kitreview"))
        return self.render_to_response(self.get_context_data(kits=kits[:100]))


class ReviewListView(SingleObjectMixin, ListView):
    queryset = (
        KitReview.objects.prefetch_related(
            Prefetch(
                "ratings",
                queryset=KitReviewPropertyRating.objects.select_related("prop"),
            )
        )
        .select_related("reviewer", "album")
        .annotate_mean_rating()
    )
    queryset_kits = ModelKit.objects.select_related("brand", "scale")
    template_name = "kitreviews/kit_review_list.html"

    def get_queryset(self):
        self.object = kit = self.get_object(queryset=self.queryset_kits)
        return super().get_queryset().filter(model_kit=kit)

    def get_context_data(self, **kwargs):
        kwargs["kit"] = self.object
        return super().get_context_data(**kwargs)


class KitReviewDetail(DetailView):
    queryset = KitReview.objects.select_related("model_kit")
    template_name = "kitreviews/kitreview_detail.html"
    context_object_name = "review"

    def get_context_data(self, **kwargs):
        kwargs.setdefault("kit", self.object.model_kit)
        kwargs["other_reviews"] = (
            self.object.model_kit.kitreview_set.select_related("reviewer", "album")
            .annotate_mean_rating()
            .exclude(pk=self.object.pk)
        )
        return super().get_context_data(**kwargs)


class LegacyRedirectView(RedirectView):
    permanent = True

    def get_redirect_url(self, *args, **kwargs):
        try:
            review_id = int(self.request.GET.get("review"))
        except (ValueError, TypeError):
            raise Http404 from None
        review = get_object_or_404(KitReview, legacy_id=review_id)
        return review.get_absolute_url()

src/brouwers/kitreviews/templates/kitreviews/add_review.html
{% extends "kitreviews/base.html" %}
{% load i18n sniplates %}

{% block eye-catcher-content %}
    <h1>
        {% trans "Add a review" %}
        <i class="pull-right fa fa-file-text-o fa-2x"></i>
    </h1>

    <p>{% blocktrans %}
        Add review to a kit here. First choose the kit you want to review. If you can't find it from the dropdown menu
        you can always add a new kit.
    {% endblocktrans %}</p>

{% endblock %}

{% block content %}

    <form action="." method="post">
        {% csrf_token %}
        {% load_widgets form='kitreviews/forms.html' %}
        {% load_widgets kits='kits/widgets.html' %}

        {{ properties.management_form }}

        {% widget 'form:non_field_errors' %}
        <fieldset class="well">
            {% form_field form.model_kit widget='kits:ModelKitSelect' label=_('Select a kit') %}
            {% form_field form.album %}
            {% form_field form.topic %}
            {% form_field form.external_topic_url %}

            {% with label_grid_offset='col-sm-offset-2' %}
                {% form_field form.show_real_name %}
            {% endwith %}
        </fieldset>

        <h2>{% trans "Review" %}</h2>
        <fieldset class="well">

            {% widget 'form:non_form_errors' %}

            {% with formset=properties %}
                {% for form in formset %}
                    {% widget 'form:non_field_errors' %}
                    {% widget 'form:ReviewPropertyRating' %}
                {% endfor %}
            {% endwith %}

            {% form_field form.raw_text label=_('Body') %}
        </fieldset>

        {% widget 'form:submit' btn_text=btn_text|default:_('Add review') %}

    </form>

{% endblock content %}

{% block modals %}
    {{ block.super }}
    {% include "kits/includes/add_kit_modal_react.html" %}
{% endblock modals %}

src/brouwers/kitreviews/templates/kitreviews/base.html
{% extends "base.html" %}
{% block data-page %}data-page="kitreviews"{% endblock %}
{% load i18n sniplates %}


{% block title %} {% trans "Kit Reviews" %}{% endblock %}


{% block body-class %}{{ block.super }} kitreviews{% endblock body-class %}


{% block eye-catcher %}
    <header class="container-fluid eye-catcher">
        <div class="container">
            {% block eye-catcher-content %}
                <h1>
                    {% trans "Kit Reviews" %}
                    <i class="pull-right fa fa-file-text-o fa-2x"></i>
                </h1>

                <p>{% blocktrans trimmed %}
                Use the kit reviews to check if the kit you have your eye on is
                worth it! And, anyone can leave reviews for a kit, so don't
                forget to contribute back.
                {% endblocktrans %}</p>
            {% endblock %}

            {% block menu %}
                <a href="{% url 'kitreviews:index' %}" class="btn bg-main-blue">
                    {% trans "Home" %}
                </a>
                {% if kit %}
                    {% url 'kitreviews:review-add' slug=kit.slug as add_url %}
                {% else %}
                    {% url 'kitreviews:add_review' as add_url %}
                {% endif %}
                <a href="{{ add_url }}" class="btn bg-main-orange">
                    <i class="fa fa-plus"></i> {% trans "Add review" %}
                </a>
            {% endblock %}
        </div>
    </header>
{% endblock %}

src/brouwers/kitreviews/templates/kitreviews/find_kit.html
{% extends "kitreviews/base.html" %}
{% load i18n sniplates static thumbnail %}

{% block content %}
    <h3>{% trans 'Find model kit(s) &dash; Enter your search parameters' %}</h3>

    <form action="{% url 'kitreviews:find_kit' %}" method="get" class="find-kit-form">
        {{ form.non_field_errors }}
        {% include "kitreviews/find_kit_form.html" %}
    </form>

    {% if form.data %}
        <h3>{% blocktrans with num_results=kits.count %}Search results ({{ num_results }}){% endblocktrans %}</h3>

        {% if kits.exists %}
            <p>{% trans "The number of search results is limited to 100 - you may need to refine your search." %}</p>
        {% endif %}

        {% if not kits.exists %}

            {% if user.is_authenticated %}

                <p class="text-center">
                    {% blocktrans trimmed %}
                        Oops, we couldn't find a kit like this in our database!
                        Would you like to add it?
                    {% endblocktrans %}
                </p>

                <div class="text-center">
                    <button data-target="#add-kit-modal" class="btn bg-main-orange">
                        {% trans 'Add kit' %}
                    </button>
                </div>

            {% else %}

                <p class="text-center">
                    {% blocktrans trimmed %}
                        Oops, we couldn't find a kit like this in our database...
                        After logging in, you can add it!
                    {% endblocktrans %}
                </p>

                <form action="{% url 'users:login' %}" method="get" class="text-center">
                    <input type="hidden" name="next" value="{{ request.get_full_path }}">
                    <button type="submit" class="btn bg-main-orange">
                        {% trans 'Login now' %}
                    </button>
                </form>

            {% endif %}

        {% endif %}

        <section class="kit__list">
            <div class="row">
                {% for kit in kits %}
                    <div class="col-sm-4 col-md-3 col-xl-2">
                        <article class="kit-preview" data-id="{{ kit.id }}">
                            <span class="h5 kit-preview__name" title="{{ kit.name }}">
                                <strong>{{ kit.name }}</strong>
                            </span>
                            <figure class="kit-preview__image">
                                {% if kit.has_box_image %}
                                    {% thumbnail kit.box_image "300x225" padding=True as im %}
                                        <img src="{{ im.url }}" class="img-responsive center-block">
                                    {% endthumbnail %}
                                {% else %}
                                    <img src="{% static "images/thumb.png" %}" class="img-responsive center-block">
                                {% endif %}
                            </figure>

                            <span class="kit-preview__details">
                            {{ kit.brand }}, {{ kit.scale }}{% if kit.category %}, {{ kit.category }}{% endif %}{% if kit.kit_number %}, <em>{{ kit.kit_number }}</em>
                                {% endif %}
                            </span>


                            {% if kit.num_reviews %}
                                <a class="button button--full button--blue"
                                   href="{% url 'kitreviews:review-list' slug=kit.slug %}">
                                    {% blocktrans trimmed count counter=kit.num_reviews %}
                                        View {{ counter }} review
                                    {% plural %}
                                        View {{ counter }} reviews
                                    {% endblocktrans %}
                                </a>
                            {% else %}
                                <span class="button button--full button--disabled">
                                    {% trans "No reviews yet" %} <i class="fa fa-frown-o"></i>
                                </span>
                            {% endif %}

                            <a class="button button--full button--orange"
                               href="{% url 'kitreviews:review-add' slug=kit.slug %}">{% trans "Add review" %}</a>

                        </article>
                    </div>
                {% endfor %}
            </div>
        </section>
    {% endif %}

{% endblock content %}


{% block modals %}
    {{ block.super }}
    {% include "kits/includes/add_kit_modal_react.html" only %}
{% endblock modals %}

src/brouwers/kitreviews/templates/kitreviews/find_kit_form.html
{% load i18n sniplates %}


<fieldset class="well">
    {% load_widgets form='horizontal.form' %}
    <div class="row">
        <div class="col-md-6">
            {% form_field form.brand %}
            {% form_field form.scale %}
        </div>
        <div class="col-md-6">
            {% form_field form.kit_name %}
            {% form_field form.kit_number %}
        </div>
    </div>
    <div class="small">
        {% trans "Find kits using the search form - all fields are optional." %}
    </div>

    <div class="button-group">

        <button type="submit" class="button button--icon button--blue {% if user.is_authenticated %}find-kit-form__button-search{% endif %}">
            <i class="fa fa-search"></i> {% trans 'Find kits' %}
        </button>

        {% if user.is_authenticated %}
            {% trans "or" %}

            <div id="find-kit-form__button-add-kit">
                {# React managed #}
                <button class="button button--icon button--orange">
                    <i class="fa fa-plus"></i> {% trans 'Add new kit' %}
                </button>
            </div>

        {% endif %}

    </div>
</fieldset>

src/brouwers/kitreviews/templates/kitreviews/forms.html
{% extends "horizontal.form" %}
{% load i18n sniplates %}


{% block Select_prop %}
{% reuse 'HiddenInput' %}
{% for val, display in choices %}
    {% if val == value %}
        <label class="control-label required col-sm-2 rating__label">{{ display }}</label>
    {% endif %}
{% endfor %}
{% endblock Select_prop %}


{% block RangeInput_rating %}
    {% reuse '_RangeInput' label=None %}
{% endblock RangeInput_rating %}


{% block ReviewPropertyRating %}
<div class="form-group clearfix rating">
    {% form_field form.prop %}
    {% form_field form.rating %}
</div>
{% endblock ReviewPropertyRating %}

src/brouwers/kitreviews/templates/kitreviews/index.html
{% extends "kitreviews/base.html" %}
{% load i18n kitreviews %}


{% block content %}

    <form action="{% url 'kitreviews:find_kit' %}" method="get" class="find-kit-form">
        {{ form.non_field_errors }}
        {% include "kitreviews/find_kit_form.html" %}
    </form>

    <section>
        <h2>{% trans "Latest reviews" %}</h2>

        {% for review in reviews %}
            {% render_review_preview review show_ratings=False %}
        {% endfor %}
    </section>

{% endblock content %}


{% block modals %}
    {{ block.super }}
    {% include "kits/includes/add_kit_modal_react.html" %}
{% endblock modals %}

src/brouwers/kitreviews/templates/kitreviews/kit_review_list.html
{% extends "kitreviews/base.html" %}
{% load i18n kitreviews sniplates static thumbnail %}


{% block content %}
<article class="kit">
    <header class="kit__header clearfix">
        {% if kit.brand.logo %}
            {% thumbnail kit.brand.logo '100x100' as im %}
                <figure class="kit__brand-logo">
                    <img src="{{ im.url }}" alt="logo-{{ kit.brand.slug }}" title="{{ kit.brand.name }}">
                </figure>
            {% endthumbnail %}
        {% else %}
            <h2 class="kit__brand-name">{{ kit.brand.name }}</h2>
        {% endif %}

        <h1 class="kit__name">
            {{ kit.name }}
            <small>
                {{ kit.kit_number }}
                {% if kit.scale %}
                    &ndash; <span class="kit__scale">{{ kit.scale }}</span>
                {% endif %}
            </small>
        </h1>
    </header>

    <figure class="kit__boxart">
        {% if kit.has_box_image %}
            {% thumbnail kit.box_image "800x600" as im %}
                <img src="{{ im.url }}" class="kit__boxart-image">
            {% endthumbnail %}
        {% else %}
            <img src="{% static "images/thumb.png" %}" class="kit__boxart-image">
        {% endif %}
    </figure>

    {% block reviews %}
    <section class="review-list">
        <h2>
            {% blocktrans trimmed count count=object_list.count %}
                There is one review
            {% plural %}
                There are {{ count }} reviews
            {% endblocktrans %}
        </h2>

        <div class="kitreviews--review-list">
            {% for review in object_list %}
                {% render_review_preview review %}
            {% endfor %}
        </div>
    </section>
    {% endblock %}
</article>
{% endblock %}

src/brouwers/kitreviews/templates/kitreviews/kitreview_detail.html
{% extends "kitreviews/kit_review_list.html" %}
{% load i18n kitreviews %}

{% block reviews %}
    <section class="review">

        <h2 id="review-body">
            {% trans "Review" %}
            <small>
                &ndash; {{ review.reviewer_name }}
                ({% blocktrans trimmed with time_ago=review.submitted_on|timesince%}
                    {{ time_ago }} ago
                {% endblocktrans %})
            </small>
        </h2>
        {% if review.topic_url or review.album %}
            <div>
                {% if review.topic_url %}
                    <a class="button button--icon button--light-blue" href="{{ review.topic_url }}">
                        <i class="fa fa-comments-o"></i>
                        {% trans "view topic" %}
                    </a>
                {% endif %}
                {% if review.album %}
                    <a class="button button--icon button--light-blue" href="{{ review.album.get_absolute_url }}">
                        <i class="fa fa-camera"></i>
                        {% trans "view album" %}
                    </a>
                {% endif %}
            </div>
        {% endif %}
        <div class="review__body">{{ review.raw_text|linebreaksbr }}</div>

        <h2>{% trans "Ratings" %}</h2>
        {% detailed_ratings review is_preview=False %}

    </section>

    {% if other_reviews %}
        <aside>
            <h2>{% trans "other reviews" %}</h2>
            {% for other_review in other_reviews %}
                {% render_review_preview other_review %}
            {% endfor %}
        </aside>
    {% endif %}
{% endblock %}